services:
  backend:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./sshKey:/app/sshKey:ro
    env_file:
      - .env
    environment:
      SSH_KEY: /app/sshKey
      LISTEN_ADDR: :8080
