import { describe, it, expect } from 'vitest'
import {
  userSourcesFor, ADVANCED_CATEGORIES, CATEGORY_ORDER, CATEGORY_ICONS, SOURCE_FILE, SOURCE_PRIORITY,
} from './constants'

// Regression test for #262 sub-bug B: on kubectl/local, dune-admin writes
// operator settings (including custom, non-schema keys) directly to
// UserGame.ini, so the "userGame" source IS a user override there. On AMP,
// UserGame.ini is regenerated by AMP itself — only "userGameOverrides" (the
// separate file dune-admin actually writes) and "amp" (curated settings
// written through the AMP API) represent real operator overrides (#212).
describe('userSourcesFor', () => {
  it('excludes userGame/userEngine on the amp control plane', () => {
    const sources = userSourcesFor('amp')
    expect(sources.has('userGame')).toBe(false)
    expect(sources.has('userEngine')).toBe(false)
    expect(sources.has('userGameOverrides')).toBe(true)
    expect(sources.has('amp')).toBe(true)
  })

  it('includes userGame/userEngine on kubectl', () => {
    const sources = userSourcesFor('kubectl')
    expect(sources.has('userGame')).toBe(true)
    expect(sources.has('userEngine')).toBe(true)
    expect(sources.has('userGameOverrides')).toBe(true)
    expect(sources.has('amp')).toBe(true)
  })

  it('includes userGame/userEngine on local', () => {
    const sources = userSourcesFor('local')
    expect(sources.has('userGame')).toBe(true)
    expect(sources.has('userEngine')).toBe(true)
  })

  it('includes userGame/userEngine when control is unknown/empty', () => {
    expect(userSourcesFor('').has('userGame')).toBe(true)
    expect(userSourcesFor('docker').has('userGame')).toBe(true)
  })
})

// #336: UserServerCustomSettings.ini is written by dune-admin on non-AMP planes
// (an operator override), but regenerated by AMP from its own config on AMP.
describe('userSourcesFor userCustom', () => {
  it('treats userCustom as an override off AMP', () => {
    expect(userSourcesFor('local').has('userCustom')).toBe(true)
    expect(userSourcesFor('kubectl').has('userCustom')).toBe(true)
  })

  it('does not treat userCustom as an override on AMP', () => {
    expect(userSourcesFor('amp').has('userCustom')).toBe(false)
  })
})

describe('UserServerCustomSettings categories', () => {
  const custom = ['Crafting & Harvesting', 'Combat & Progression', 'Survival', 'Building & Landsraad']

  it('shows them by default, ordered after the curated categories, with icons', () => {
    for (const cat of custom) {
      expect(ADVANCED_CATEGORIES.has(cat)).toBe(true)
      expect(CATEGORY_ORDER.indexOf(cat)).toBeGreaterThan(CATEGORY_ORDER.indexOf('Server Identity'))
      expect(CATEGORY_ICONS[cat]).toBeTruthy()
    }
  })

  it('labels the new file layer', () => {
    expect(SOURCE_FILE.userCustom).toBe('UserServerCustomSettings.ini')
    expect(SOURCE_PRIORITY).toContain('userCustom')
  })
})
