export type TabId
  = | 'dashboard'
    | 'battlegroup'
    | 'players'
    | 'database'
    | 'logs'
    | 'blueprints'
    | 'bases'
    | 'guilds'
    | 'landsraad'
    | 'storage'
    | 'livemap'
    | 'server'
    | 'director'
    | 'market'
    | 'welcome'
    | 'events'
    | 'battlepass'
    | 'permissions'
    | 'diagnostics'

export type DbSection = 'backups' | 'tables' | 'describe' | 'sample' | 'search' | 'sql'
export type WelcomeSection = 'config' | 'packages' | 'grants'
